<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '9225a0386d6ac51467d73ac98777af38' => $baseDir . '/includes/avatar-privacy-functions.php',
    '96cc9366f0f8a682f3b272c65c21b84f' => $baseDir . '/includes/avatar-privacy/functions.php',
    '664e375fee598657b31fb4bcd80b6963' => $baseDir . '/includes/avatar-privacy/tools/functions.php',
);
